# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://koyilu.github.io
date_format: "ordinal"
title: 可以宅基地
subtitle: "柑橘味气息的肥宅"
description: "一个肥宅的个人博客"
keywords: 可以宅基地, 肥宅, 宅, 基地
timezone: Asia/Hangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Keyi Lu
organization: koyilu.github.io
organization_url: https://koyilu.github.io
github_username: koyilu
location: Hangzhou, China
email: koryelu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: koyilu/koyilu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: koyilu
    repo: koyilu.github.io
    oauth:
        client_id: 124cf8dfa2c95f5e9c2a
        client_secret: ac0019ff20434202711635a5911fa8afe5974c52
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: koyilu
    repo: koyilu.github.io
    clientID: 124cf8dfa2c95f5e9c2a
    clientSecret: ac0019ff20434202711635a5911fa8afe5974c52
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-120220473-1
